#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

for pid in /proc/*/; do
    pid=${pid%/}
    if [[ -f "$pid/cmdline" ]] && grep -q "bash" "$pid/cmdline"; then
        echo "$(basename "$pid") bash"
    fi
done


