#!/usr/bin/env bash
#script that displays numbers from 1 to 100.

#for (( i=1; i<=100; i++ ))
i=1
while [ $i -le 100 ]
do
	case $((i % 15)) in 
		0)
			echo "Fizzbuzz"
			;;
		3|6|9|12)
			echo "Fizz"
			;;
		5|10)
			echo "Buzz"
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done
