#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.


while IFS=: read -r username x userid groupid gecos homedir shell;
do
	echo "$username:$userid:$homedir"
			
done < /etc/passwd
