#!/usr/bin/env bash
# A Bash Script that display the content of the directory
#in a list format
#Where only the part of the name after the first dash is displayed


for i in *; 
do
	echo "${i#*-}"
done


