#!/usr/bin/env bash
#Write a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
@: Only use: ssh single character flags
@: without using: -l
@: No need of a private key protected by a passphrase


ssh -i ~/.ssh/shool ubuntu@192.168.8.101
